apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  namespace: development
  labels:
    app: db
spec:
  containers:
  - name: postgres
    image: postgres:13
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: social_book_db
    - name: POSTGRES_USER
      value: yushi
    - name: POSTGRES_PASSWORD
      value: "123456"
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: development
  labels:
    app: db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: db